#define RGBLIGHT_LAYERS
#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_TWINKLE
#undef RGBLIGHT_EFFECT_BREATHING

#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_SLEEP

#define RGBLIGHT_MAX_LAYERS 6

#define MOUSEKEY_DELAY 10
#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_MOVE_DELTA 8
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_TIME_TO_MAX 30
#define MOUSEKEY_WHEEL_DELAY 10
#define MOUSEKEY_WHEEL_INTERVAL 80
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#define AUTO_SHIFT_REPEAT
#define AUTO_SHIFT_TIMEOUT 175

#define TAPPING_TERM 200

#define COMBO_SHOULD_TRIGGER
#define COMBO_COUNT 26

#define USB_MAX_POWER_CONSUMPTION 100

